version: '3.1'

services:
    db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: example    
    web:
      build: .
      restart: always
      volumes: 
        - .:/code
      environment:
        POSTGRES: "postgres://postgres:example@db/carrental?sslmode=disable"
      links:
        - db
      #ports:
      # - "8082:8082"
      expose:
        - '8082'
    
    balancer:
      image: dockercloud/haproxy
      links:
        - web
      environment:
        STATS_AUTH: 'stats:stats'
        EXTRA_DEFAULT_SETTINGS: timeout tunnel 1h, timeout client 30s
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - '80:80'
        - '1936:1936'
     

      
