package storage

var (
	sqlTrack = `INSERT INTO "public"."LOCATION" ("CAR","POINT") VALUES(  
		(SELECT "ID" FROM "CAR" WHERE "REGNUM"=$1),
		POINT($2,$3))`

	sqlFindByID = `SELECT c."ID", c."REGNUM", c."MODEL", m."NAME" "MODELNAME" FROM "CAR" c ,"MODEL" m
	WHERE
		c."MODEL" = m."ID"
		and c."ID"=$1`

	sqlRentAction = `INSERT INTO "RENTAL"("TSWORK","OPER","CAR","DEPT","AGENTNAME") VALUES (
		CURRENT_TIMESTAMP,$1,
		(SELECT "CAR"."ID" from "CAR" WHERE  "CAR"."REGNUM" = $2),
		(SELECT "DEPARTMENT"."ID" FROM "DEPARTMENT" WHERE "DEPARTMENT"."NAME" = $3),
		$4)`

	sqlRentJornal = `SELECT R."ID", T."NAME" "TYPE",M."NAME" "MODEL",C."REGNUM" "RN",R."TSWORK" "DATEOPER",
	R."AGENTNAME" "AGENT" ,
  CASE R."OPER" WHEN 1 THEN 'rent' ELSE 'return' END "OPER",
	D."NAME" "DEPT"
FROM "CARTYPE" T, "MODEL" M, "CAR" C, "DEPARTMENT" D, "RENTAL" R
WHERE R."CAR" = C."ID"
	AND T."ID" = M."CTYPE"
	AND C."MODEL" = M."ID"
	AND D."ID" = R."DEPT"
	AND ($1::text = '' OR $1::text=C."REGNUM")
ORDER BY R."ID" DESC`

	sqlCars = `SELECT "CAR"."ID","CAR"."REGNUM","MODEL"."NAME" "MODEL",
	"CARTYPE"."CODE" "TYPECODE","CARTYPE"."NAME" "TYPENAME"
FROM
	"CAR","MODEL","CARTYPE"
WHERE
	"MODEL"."ID"="CAR"."MODEL" AND "MODEL"."CTYPE"="CARTYPE"."ID"`
)
