package storage

var (
	sqlTrack = `INSERT INTO "public"."LOCATION" ("CAR","POINT") VALUES(  
		(SELECT "ID" FROM "CAR" WHERE "REGNUM"=$1),
		POINT($2,$3))`

	sqlFindByID = `SELECT c."ID", c."REGNUM", c."MODEL", m."NAME" "MODELNAME" FROM "CAR" c ,"MODEL" m
	WHERE
		c."MODEL" = m."ID"
		and c."ID"=$1`

	sqlRentAction = `INSERT INTO "RENTAL"("TSWORK","OPER","CAR","DEPT","AGENTNAME") VALUES (
		CURRENT_TIMESTAMP,$1,
		(SELECT "CAR"."ID" from "CAR" WHERE  "CAR"."REGNUM" = $2),
		(SELECT "DEPARTMENT"."ID" FROM "DEPARTMENT" WHERE "DEPARTMENT"."NAME" = $3),
		$4) returning "RENTAL"."ID"`

	sqlRentJornal = `SELECT R."ID", T."NAME" "TYPE",M."NAME" "MODEL",C."REGNUM" "RN",R."TSWORK" "DATEOPER",
	R."AGENTNAME" "AGENT" ,
  CASE R."OPER" WHEN 1 THEN 'rent' ELSE 'return' END "OPER",
	D."NAME" "DEPT"
FROM "CARTYPE" T, "MODEL" M, "CAR" C, "DEPARTMENT" D, "RENTAL" R
WHERE R."CAR" = C."ID"
	AND T."ID" = M."CTYPE"
	AND C."MODEL" = M."ID"
	AND D."ID" = R."DEPT"
	AND ($1::text = '' OR $1::text=C."REGNUM")
ORDER BY R."ID" DESC`

	sqlCars = `SELECT "CAR"."ID","CAR"."REGNUM","MODEL"."NAME" "MODEL",
	"CARTYPE"."CODE" "TYPECODE","CARTYPE"."NAME" "TYPENAME"
FROM
	"CAR","MODEL","CARTYPE"
WHERE
	"MODEL"."ID"="CAR"."MODEL" AND "MODEL"."CTYPE"="CARTYPE"."ID"`

	sqlDepartments = `SELECT "ID", "NAME" FROM "DEPARTMENT"`

	sqlCarInfo = `SELECT
	C."ID",C."REGNUM",M."NAME" "MODEL", T."NAME" "TYPE", T."CODE" "TYPECODE"
	,(SELECT D."NAME" FROM "DEPARTMENT" D WHERE  D."ID" = coalesce(G."DEPT",R."DEPT")) "DEPTNAME"
	,coalesce(R."TSWORK",CURRENT_TIMESTAMP) "TSWORK"
	,coalesce(R."OPER",0) "OPER"
	,coalesce(R."AGENTNAME",'') "AGENTNAME"
FROM
	"CARTYPE" T, "MODEL" M,
	"CAR" C LEFT JOIN "CARGOODS" G on G."CAR" = C."ID"
				  LEFT JOIN "CARRENT" CR on CR."CAR" = C."ID"
	        LEFT JOIN "RENTAL" R on R."ID" = CR."IDRENTAL"
WHERE
  C."REGNUM" = $1
  AND C."MODEL" = M."ID"
  AND M."CTYPE" = T."ID";`

	sqlStatsByModel = `SELECT
	D."NAME" ,M."NAME" "ENTITY",COUNT(1) cnt, EXTRACT(EPOCH FROM  sum(RS."TSWORK" - RE."TSWORK")) "DURATION"
FROM "RENTAL" RS,"RENTAL" RE, "RENTALLINKS" L,
	"CAR" C, "MODEL" M,"DEPARTMENT" D
WHERE
	L."ROUT" = RS."ID"
	AND L."RIN" = RE."ID"
	AND RS."CAR"=C."ID"
	AND C."MODEL"=m."ID"
	AND D."ID" = RE."DEPT"
GROUP BY  RE."DEPT", D."NAME", M."NAME";`

	sqlStatsByType = `SELECT
	D."NAME" ,T."NAME" "ENTITY",COUNT(1) cnt, EXTRACT(EPOCH FROM  sum(RS."TSWORK" - RE."TSWORK")) "DURATION"
FROM "RENTAL" RS,"RENTAL" RE, "RENTALLINKS" L,
	"CAR" C, "MODEL" M,"CARTYPE" T,"DEPARTMENT" D
WHERE
	L."ROUT" = RS."ID"
	AND L."RIN" = RE."ID"
	AND RS."CAR"=C."ID"
	AND C."MODEL"=m."ID"
	AND T."ID" = M."CTYPE"
	AND D."ID" = RE."DEPT"
GROUP BY  RE."DEPT", D."NAME", T."NAME";`
)
