CREATE TABLE "AGENT"
(
    "ID" INTEGER DEFAULT nextval('"AGENT_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR NOT NULL,
    "FAMILY" VARCHAR NOT NULL,
    "MIDDLENAME" VARCHAR,
    "CODE" VARCHAR NOT NULL
);
COMMENT ON COLUMN "AGENT"."CODE" IS 'м.б. СНИЛС или др. для однозначной идентификации';
CREATE UNIQUE INDEX "AGENT_CODE" ON "AGENT" ("CODE");
CREATE TABLE "CAR"
(
    "ID" INTEGER DEFAULT nextval('"CAR_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "MODEL" INTEGER NOT NULL,
    "REGNUM" VARCHAR(20) NOT NULL,
    CONSTRAINT car_model_fk FOREIGN KEY ("MODEL") REFERENCES "MODEL" ("ID")
);
COMMENT ON COLUMN "CAR"."REGNUM" IS 'Рег. Номер';
CREATE UNIQUE INDEX car_regnum_uindex ON "CAR" ("REGNUM");
CREATE TABLE "CARGOODS"
(
    "ID" INTEGER DEFAULT nextval('"CARGOODS_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "DEPT" INTEGER NOT NULL,
    "CAR" INTEGER NOT NULL,
    CONSTRAINT cargoods_department_id_fk FOREIGN KEY ("DEPT") REFERENCES "DEPARTMENT" ("ID"),
    CONSTRAINT cargoods_car_id_fk FOREIGN KEY ("CAR") REFERENCES "CAR" ("ID")
);
COMMENT ON COLUMN "CARGOODS"."DEPT" IS 'Подразделение';
COMMENT ON COLUMN "CARGOODS"."CAR" IS 'ТС';
CREATE UNIQUE INDEX cargoods_car_idx ON "CARGOODS" ("CAR");
CREATE TABLE "CARTYPE"
(
    "ID" INTEGER DEFAULT nextval('"CARTYPE_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(30) NOT NULL,
    "CODE" VARCHAR(30) NOT NULL
);
CREATE UNIQUE INDEX "CARTYPE_NAME" ON "CARTYPE" ("NAME");
CREATE UNIQUE INDEX "CARTYPE_CODE" ON "CARTYPE" ("CODE");
CREATE TABLE "DEPARTMENT"
(
    "ID" INTEGER DEFAULT nextval('"DEPARTMENT_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR NOT NULL
);
CREATE UNIQUE INDEX "DEPARTMENT_Name" ON "DEPARTMENT" ("NAME");
CREATE TABLE "LOCATION"
(
    "ID" INTEGER DEFAULT nextval('"LOCATION_ID_seq"'::regclass) NOT NULL,
    "TS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "CAR" INTEGER NOT NULL,
    "POINT" POINT NOT NULL,
    CONSTRAINT "LOCATION_CAR_fkey" FOREIGN KEY ("CAR") REFERENCES "CAR" ("ID")
);
COMMENT ON COLUMN "LOCATION"."TS" IS 'Дата Время';
COMMENT ON COLUMN "LOCATION"."POINT" IS 'Координаты';
CREATE TABLE "MODEL"
(
    "ID" INTEGER DEFAULT nextval('"MODEL_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "CTYPE" INTEGER NOT NULL,
    CONSTRAINT "MODEL_CTYPE_fkey" FOREIGN KEY ("CTYPE") REFERENCES "CARTYPE" ("ID")
);
CREATE TABLE "RENTAL"
(
    "ID" INTEGER DEFAULT nextval('"RENTAL_ID_seq"'::regclass) PRIMARY KEY NOT NULL,
    "CAR" INTEGER NOT NULL,
    "TS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TSWORK" TIMESTAMP NOT NULL,
    "OPER" SMALLINT DEFAULT '0'::smallint NOT NULL,
    "DEPT" INTEGER NOT NULL,
    "AGENT" INTEGER NOT NULL,
    CONSTRAINT "RENTAL_CAR_fkey" FOREIGN KEY ("CAR") REFERENCES "CAR" ("ID"),
    CONSTRAINT "RENTAL_DEPT_fkey" FOREIGN KEY ("DEPT") REFERENCES "DEPARTMENT" ("ID"),
    CONSTRAINT rental_agent_id_fk FOREIGN KEY ("AGENT") REFERENCES "AGENT" ("ID")
);
CREATE FUNCTION increment(i INTEGER) RETURNS INTEGER;
CREATE FUNCTION rental_goods() RETURNS TRIGGER;